#!/bin/sh
set -e

case "$1" in
    remove|purge)
        if command -v update-alternatives >/dev/null 2>&1; then
            update-alternatives --remove \
                default.plymouth \
                /usr/share/plymouth/themes/linus/linus.plymouth 2>/dev/null || true
        fi
        ;;
esac

#DEBHELPER#
exit 0
