---
# Systemd units to enable in the installed target.
services:
    - name: NetworkManager
      enabled: true
    - name: greetd
      enabled: true
    - name: bluetooth
      enabled: true
    - name: fstrim.timer
      enabled: true

targets:
    - name: graphical
      enabled: true
