---
# User creation module.

defaultGroups:
    - audio
    - video
    - netdev
    - plugdev
    - bluetooth
    - lpadmin
    - scanner
    - dialout
    - input
    - render

# Group used for passwordless sudo.
sudoersGroup:    sudo

# Group used when autologin is enabled.
autologinGroup:  autologin

# Allow (but do not require) setting a root password.
setRootPassword: true

# Pre-fill the root password with the user password.
doReusePassword: true

passwordRequirements:
    minLength: -1
    maxLength: -1
    libpwquality:
        - minlen=0

allowWeakPasswords: false
