---
showSupportUrl:      true
showKnownIssuesUrl:  true
showReleaseNotesUrl: true
showDonateUrl:       false

requirements:
    # Storage is in GiB; RAM is in GiB.
    requiredStorage: 10.0
    requiredRam:     2.0
    check:
        - storage
        - ram
        - power
        - root
    # Installation is blocked if these fail.
    required:
        - storage
        - ram
        - root
